LogLevel info

Listen 0.0.0.0:631
Listen /run/cups/cups.sock

DefaultEncription Required
WebInterface Yes
Browsing On
DefaultAuthType Basic

ServerCertificate /etc/cups/ssl/tls.crt
ServerKey /etc/cups/ssl/tls.key

SSLProtocol TLSv1.2 TLSv1.3
SSLHonorCipherOrder Yes

<Location />
  Order allow,deny
  Allow all
</Location>

<Location /admin>
 AuthType Basic
 AuthClass System
 Require user admin
 Order allow,deny
 Allow all
</Location>

ServerAlias *
